### ISSUE TITLE
Is the license GPL or MIT?

### ISSUE THREAD

**Issue by corburn** [tacorna/taco#22]
Hello, I am updating the bioconda package for this repository. The [setup.py](https://github.com/tacorna/taco/blob/c191ecd356c0d7d72ac7f3c7c374fb7804cf56ef/setup.py#L15) file lists the license as GPL, but on the [website](http://tacorna.github.io/#license) it is MIT. Can you confirm if the license is GPL and/or MIT? If it is GPL, what is the license version? Could you also [add the license to the repository](https://help.github.com/articles/adding-a-license-to-a-repository/)?

**Comment by balajipandian** [comment]
Hello, the code is under the MIT license. Sorry for the conflicting sources, the website and code have been updated to reflect this.
