### ISSUE TITLE
No module named taco.lib.run

### ISSUE THREAD

**Issue by TaoHJiang** [tacorna/taco#28]
Hi,
I get the follwoing when I execute "python2.7 taco_run.py -h". 

Traceback (most recent call last):
  File "taco_run.py", line 8, in <module>
    from taco.lib.run import Run
ImportError: No module named taco.lib.run

**Comment by mkiyer** [comment]
Is this a problem with your PYTHONPATH? Thanks -- we are working on a python 3 version. Hopefully very soon.
